language: javascript
notifications:
  email:
    recipients:
      - bconez@up.edu.ph
      - yannahdenise.oreo@gmail.com
      - gclunesa@up.edu.ph
    on_success: never # default: change
    on_failure: always # default: always
