language: javascript

install: true


script: ant build

notifications:
  email:
    recipients:
      - bconez@up.edu.ph
      - yannahdenise.oreo@gmail.com
      - gclunesa@up.edu.ph
    on_success: always # default: change
    on_failure: always # default: always
